// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// AppInventory is an object representing the database table.
type AppInventory struct {
	ID           int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DRCCheckTime time.Time `boil:"drc_check_time" json:"drc_check_time" toml:"drc_check_time" yaml:"drc_check_time"`
	AppID        int64     `boil:"app_id" json:"app_id" toml:"app_id" yaml:"app_id"`
	InventoryID  int64     `boil:"inventory_id" json:"inventory_id" toml:"inventory_id" yaml:"inventory_id"`

	R *appInventoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L appInventoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AppInventoryColumns = struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	DRCCheckTime string
	AppID        string
	InventoryID  string
}{
	ID:           "id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DRCCheckTime: "drc_check_time",
	AppID:        "app_id",
	InventoryID:  "inventory_id",
}

// appInventoryR is where relationships are stored.
type appInventoryR struct {
}

// appInventoryL is where Load methods for each relationship are stored.
type appInventoryL struct{}

var (
	appInventoryColumns               = []string{"id", "created_at", "updated_at", "drc_check_time", "app_id", "inventory_id"}
	appInventoryColumnsWithoutDefault = []string{}
	appInventoryColumnsWithDefault    = []string{"id", "created_at", "updated_at", "drc_check_time", "app_id", "inventory_id"}
	appInventoryPrimaryKeyColumns     = []string{"id"}
)

type (
	// AppInventorySlice is an alias for a slice of pointers to AppInventory.
	// This should generally be used opposed to []AppInventory.
	AppInventorySlice []*AppInventory
	// AppInventoryHook is the signature for custom AppInventory hook methods
	AppInventoryHook func(boil.Executor, *AppInventory) error

	appInventoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	appInventoryType                 = reflect.TypeOf(&AppInventory{})
	appInventoryMapping              = queries.MakeStructMapping(appInventoryType)
	appInventoryPrimaryKeyMapping, _ = queries.BindMapping(appInventoryType, appInventoryMapping, appInventoryPrimaryKeyColumns)
	appInventoryInsertCacheMut       sync.RWMutex
	appInventoryInsertCache          = make(map[string]insertCache)
	appInventoryUpdateCacheMut       sync.RWMutex
	appInventoryUpdateCache          = make(map[string]updateCache)
	appInventoryUpsertCacheMut       sync.RWMutex
	appInventoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var appInventoryBeforeInsertHooks []AppInventoryHook
var appInventoryBeforeUpdateHooks []AppInventoryHook
var appInventoryBeforeDeleteHooks []AppInventoryHook
var appInventoryBeforeUpsertHooks []AppInventoryHook

var appInventoryAfterInsertHooks []AppInventoryHook
var appInventoryAfterSelectHooks []AppInventoryHook
var appInventoryAfterUpdateHooks []AppInventoryHook
var appInventoryAfterDeleteHooks []AppInventoryHook
var appInventoryAfterUpsertHooks []AppInventoryHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AppInventory) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AppInventory) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AppInventory) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AppInventory) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AppInventory) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AppInventory) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AppInventory) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AppInventory) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AppInventory) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range appInventoryAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAppInventoryHook registers your hook function for all future operations.
func AddAppInventoryHook(hookPoint boil.HookPoint, appInventoryHook AppInventoryHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		appInventoryBeforeInsertHooks = append(appInventoryBeforeInsertHooks, appInventoryHook)
	case boil.BeforeUpdateHook:
		appInventoryBeforeUpdateHooks = append(appInventoryBeforeUpdateHooks, appInventoryHook)
	case boil.BeforeDeleteHook:
		appInventoryBeforeDeleteHooks = append(appInventoryBeforeDeleteHooks, appInventoryHook)
	case boil.BeforeUpsertHook:
		appInventoryBeforeUpsertHooks = append(appInventoryBeforeUpsertHooks, appInventoryHook)
	case boil.AfterInsertHook:
		appInventoryAfterInsertHooks = append(appInventoryAfterInsertHooks, appInventoryHook)
	case boil.AfterSelectHook:
		appInventoryAfterSelectHooks = append(appInventoryAfterSelectHooks, appInventoryHook)
	case boil.AfterUpdateHook:
		appInventoryAfterUpdateHooks = append(appInventoryAfterUpdateHooks, appInventoryHook)
	case boil.AfterDeleteHook:
		appInventoryAfterDeleteHooks = append(appInventoryAfterDeleteHooks, appInventoryHook)
	case boil.AfterUpsertHook:
		appInventoryAfterUpsertHooks = append(appInventoryAfterUpsertHooks, appInventoryHook)
	}
}

// OneP returns a single appInventory record from the query, and panics on error.
func (q appInventoryQuery) OneP() *AppInventory {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single appInventory record from the query.
func (q appInventoryQuery) One() (*AppInventory, error) {
	o := &AppInventory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for app_inventory")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all AppInventory records from the query, and panics on error.
func (q appInventoryQuery) AllP() AppInventorySlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all AppInventory records from the query.
func (q appInventoryQuery) All() (AppInventorySlice, error) {
	var o []*AppInventory

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AppInventory slice")
	}

	if len(appInventoryAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all AppInventory records in the query, and panics on error.
func (q appInventoryQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all AppInventory records in the query.
func (q appInventoryQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count app_inventory rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q appInventoryQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q appInventoryQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if app_inventory exists")
	}

	return count > 0, nil
}

// AppInventoriesG retrieves all records.
func AppInventoriesG(mods ...qm.QueryMod) appInventoryQuery {
	return AppInventories(boil.GetDB(), mods...)
}

// AppInventories retrieves all the records using an executor.
func AppInventories(exec boil.Executor, mods ...qm.QueryMod) appInventoryQuery {
	mods = append(mods, qm.From("`app_inventory`"))
	return appInventoryQuery{NewQuery(exec, mods...)}
}

// FindAppInventoryG retrieves a single record by ID.
func FindAppInventoryG(id int64, selectCols ...string) (*AppInventory, error) {
	return FindAppInventory(boil.GetDB(), id, selectCols...)
}

// FindAppInventoryGP retrieves a single record by ID, and panics on error.
func FindAppInventoryGP(id int64, selectCols ...string) *AppInventory {
	retobj, err := FindAppInventory(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindAppInventory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAppInventory(exec boil.Executor, id int64, selectCols ...string) (*AppInventory, error) {
	appInventoryObj := &AppInventory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `app_inventory` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(appInventoryObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from app_inventory")
	}

	return appInventoryObj, nil
}

// FindAppInventoryP retrieves a single record by ID with an executor, and panics on error.
func FindAppInventoryP(exec boil.Executor, id int64, selectCols ...string) *AppInventory {
	retobj, err := FindAppInventory(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *AppInventory) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *AppInventory) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *AppInventory) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *AppInventory) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no app_inventory provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(appInventoryColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	appInventoryInsertCacheMut.RLock()
	cache, cached := appInventoryInsertCache[key]
	appInventoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			appInventoryColumns,
			appInventoryColumnsWithDefault,
			appInventoryColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(appInventoryType, appInventoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(appInventoryType, appInventoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `app_inventory` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `app_inventory` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `app_inventory` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, appInventoryPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into app_inventory")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == appInventoryMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for app_inventory")
	}

CacheNoHooks:
	if !cached {
		appInventoryInsertCacheMut.Lock()
		appInventoryInsertCache[key] = cache
		appInventoryInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single AppInventory record. See Update for
// whitelist behavior description.
func (o *AppInventory) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single AppInventory record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *AppInventory) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the AppInventory, and panics on error.
// See Update for whitelist behavior description.
func (o *AppInventory) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the AppInventory.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *AppInventory) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	appInventoryUpdateCacheMut.RLock()
	cache, cached := appInventoryUpdateCache[key]
	appInventoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			appInventoryColumns,
			appInventoryPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update app_inventory, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `app_inventory` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, appInventoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(appInventoryType, appInventoryMapping, append(wl, appInventoryPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update app_inventory row")
	}

	if !cached {
		appInventoryUpdateCacheMut.Lock()
		appInventoryUpdateCache[key] = cache
		appInventoryUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q appInventoryQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q appInventoryQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for app_inventory")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o AppInventorySlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o AppInventorySlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o AppInventorySlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AppInventorySlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), appInventoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `app_inventory` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, appInventoryPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in appInventory slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *AppInventory) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *AppInventory) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *AppInventory) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *AppInventory) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no app_inventory provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(appInventoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	appInventoryUpsertCacheMut.RLock()
	cache, cached := appInventoryUpsertCache[key]
	appInventoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			appInventoryColumns,
			appInventoryColumnsWithDefault,
			appInventoryColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			appInventoryColumns,
			appInventoryPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert app_inventory, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "app_inventory", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `app_inventory` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(appInventoryType, appInventoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(appInventoryType, appInventoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for app_inventory")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == appInventoryMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for app_inventory")
	}

CacheNoHooks:
	if !cached {
		appInventoryUpsertCacheMut.Lock()
		appInventoryUpsertCache[key] = cache
		appInventoryUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single AppInventory record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *AppInventory) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single AppInventory record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *AppInventory) DeleteG() error {
	if o == nil {
		return errors.New("models: no AppInventory provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single AppInventory record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *AppInventory) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single AppInventory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AppInventory) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no AppInventory provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), appInventoryPrimaryKeyMapping)
	sql := "DELETE FROM `app_inventory` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from app_inventory")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q appInventoryQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q appInventoryQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no appInventoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from app_inventory")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o AppInventorySlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o AppInventorySlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no AppInventory slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o AppInventorySlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AppInventorySlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no AppInventory slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(appInventoryBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), appInventoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `app_inventory` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, appInventoryPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from appInventory slice")
	}

	if len(appInventoryAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *AppInventory) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *AppInventory) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *AppInventory) ReloadG() error {
	if o == nil {
		return errors.New("models: no AppInventory provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AppInventory) Reload(exec boil.Executor) error {
	ret, err := FindAppInventory(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AppInventorySlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AppInventorySlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AppInventorySlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty AppInventorySlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AppInventorySlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	appInventories := AppInventorySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), appInventoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `app_inventory`.* FROM `app_inventory` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, appInventoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&appInventories)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AppInventorySlice")
	}

	*o = appInventories

	return nil
}

// AppInventoryExists checks if the AppInventory row exists.
func AppInventoryExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `app_inventory` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if app_inventory exists")
	}

	return exists, nil
}

// AppInventoryExistsG checks if the AppInventory row exists.
func AppInventoryExistsG(id int64) (bool, error) {
	return AppInventoryExists(boil.GetDB(), id)
}

// AppInventoryExistsGP checks if the AppInventory row exists. Panics on error.
func AppInventoryExistsGP(id int64) bool {
	e, err := AppInventoryExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// AppInventoryExistsP checks if the AppInventory row exists. Panics on error.
func AppInventoryExistsP(exec boil.Executor, id int64) bool {
	e, err := AppInventoryExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
