// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// AppPlaybook is an object representing the database table.
type AppPlaybook struct {
	ID           int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DRCCheckTime time.Time `boil:"drc_check_time" json:"drc_check_time" toml:"drc_check_time" yaml:"drc_check_time"`
	AppID        int64     `boil:"app_id" json:"app_id" toml:"app_id" yaml:"app_id"`
	PlaybookID   int64     `boil:"playbook_id" json:"playbook_id" toml:"playbook_id" yaml:"playbook_id"`

	R *appPlaybookR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L appPlaybookL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AppPlaybookColumns = struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	DRCCheckTime string
	AppID        string
	PlaybookID   string
}{
	ID:           "id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DRCCheckTime: "drc_check_time",
	AppID:        "app_id",
	PlaybookID:   "playbook_id",
}

// appPlaybookR is where relationships are stored.
type appPlaybookR struct {
}

// appPlaybookL is where Load methods for each relationship are stored.
type appPlaybookL struct{}

var (
	appPlaybookColumns               = []string{"id", "created_at", "updated_at", "drc_check_time", "app_id", "playbook_id"}
	appPlaybookColumnsWithoutDefault = []string{}
	appPlaybookColumnsWithDefault    = []string{"id", "created_at", "updated_at", "drc_check_time", "app_id", "playbook_id"}
	appPlaybookPrimaryKeyColumns     = []string{"id"}
)

type (
	// AppPlaybookSlice is an alias for a slice of pointers to AppPlaybook.
	// This should generally be used opposed to []AppPlaybook.
	AppPlaybookSlice []*AppPlaybook
	// AppPlaybookHook is the signature for custom AppPlaybook hook methods
	AppPlaybookHook func(boil.Executor, *AppPlaybook) error

	appPlaybookQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	appPlaybookType                 = reflect.TypeOf(&AppPlaybook{})
	appPlaybookMapping              = queries.MakeStructMapping(appPlaybookType)
	appPlaybookPrimaryKeyMapping, _ = queries.BindMapping(appPlaybookType, appPlaybookMapping, appPlaybookPrimaryKeyColumns)
	appPlaybookInsertCacheMut       sync.RWMutex
	appPlaybookInsertCache          = make(map[string]insertCache)
	appPlaybookUpdateCacheMut       sync.RWMutex
	appPlaybookUpdateCache          = make(map[string]updateCache)
	appPlaybookUpsertCacheMut       sync.RWMutex
	appPlaybookUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var appPlaybookBeforeInsertHooks []AppPlaybookHook
var appPlaybookBeforeUpdateHooks []AppPlaybookHook
var appPlaybookBeforeDeleteHooks []AppPlaybookHook
var appPlaybookBeforeUpsertHooks []AppPlaybookHook

var appPlaybookAfterInsertHooks []AppPlaybookHook
var appPlaybookAfterSelectHooks []AppPlaybookHook
var appPlaybookAfterUpdateHooks []AppPlaybookHook
var appPlaybookAfterDeleteHooks []AppPlaybookHook
var appPlaybookAfterUpsertHooks []AppPlaybookHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *AppPlaybook) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *AppPlaybook) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *AppPlaybook) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *AppPlaybook) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *AppPlaybook) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *AppPlaybook) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *AppPlaybook) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *AppPlaybook) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *AppPlaybook) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range appPlaybookAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddAppPlaybookHook registers your hook function for all future operations.
func AddAppPlaybookHook(hookPoint boil.HookPoint, appPlaybookHook AppPlaybookHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		appPlaybookBeforeInsertHooks = append(appPlaybookBeforeInsertHooks, appPlaybookHook)
	case boil.BeforeUpdateHook:
		appPlaybookBeforeUpdateHooks = append(appPlaybookBeforeUpdateHooks, appPlaybookHook)
	case boil.BeforeDeleteHook:
		appPlaybookBeforeDeleteHooks = append(appPlaybookBeforeDeleteHooks, appPlaybookHook)
	case boil.BeforeUpsertHook:
		appPlaybookBeforeUpsertHooks = append(appPlaybookBeforeUpsertHooks, appPlaybookHook)
	case boil.AfterInsertHook:
		appPlaybookAfterInsertHooks = append(appPlaybookAfterInsertHooks, appPlaybookHook)
	case boil.AfterSelectHook:
		appPlaybookAfterSelectHooks = append(appPlaybookAfterSelectHooks, appPlaybookHook)
	case boil.AfterUpdateHook:
		appPlaybookAfterUpdateHooks = append(appPlaybookAfterUpdateHooks, appPlaybookHook)
	case boil.AfterDeleteHook:
		appPlaybookAfterDeleteHooks = append(appPlaybookAfterDeleteHooks, appPlaybookHook)
	case boil.AfterUpsertHook:
		appPlaybookAfterUpsertHooks = append(appPlaybookAfterUpsertHooks, appPlaybookHook)
	}
}

// OneP returns a single appPlaybook record from the query, and panics on error.
func (q appPlaybookQuery) OneP() *AppPlaybook {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single appPlaybook record from the query.
func (q appPlaybookQuery) One() (*AppPlaybook, error) {
	o := &AppPlaybook{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for app_playbook")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all AppPlaybook records from the query, and panics on error.
func (q appPlaybookQuery) AllP() AppPlaybookSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all AppPlaybook records from the query.
func (q appPlaybookQuery) All() (AppPlaybookSlice, error) {
	var o []*AppPlaybook

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to AppPlaybook slice")
	}

	if len(appPlaybookAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all AppPlaybook records in the query, and panics on error.
func (q appPlaybookQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all AppPlaybook records in the query.
func (q appPlaybookQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count app_playbook rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q appPlaybookQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q appPlaybookQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if app_playbook exists")
	}

	return count > 0, nil
}

// AppPlaybooksG retrieves all records.
func AppPlaybooksG(mods ...qm.QueryMod) appPlaybookQuery {
	return AppPlaybooks(boil.GetDB(), mods...)
}

// AppPlaybooks retrieves all the records using an executor.
func AppPlaybooks(exec boil.Executor, mods ...qm.QueryMod) appPlaybookQuery {
	mods = append(mods, qm.From("`app_playbook`"))
	return appPlaybookQuery{NewQuery(exec, mods...)}
}

// FindAppPlaybookG retrieves a single record by ID.
func FindAppPlaybookG(id int64, selectCols ...string) (*AppPlaybook, error) {
	return FindAppPlaybook(boil.GetDB(), id, selectCols...)
}

// FindAppPlaybookGP retrieves a single record by ID, and panics on error.
func FindAppPlaybookGP(id int64, selectCols ...string) *AppPlaybook {
	retobj, err := FindAppPlaybook(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindAppPlaybook retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAppPlaybook(exec boil.Executor, id int64, selectCols ...string) (*AppPlaybook, error) {
	appPlaybookObj := &AppPlaybook{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `app_playbook` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(appPlaybookObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from app_playbook")
	}

	return appPlaybookObj, nil
}

// FindAppPlaybookP retrieves a single record by ID with an executor, and panics on error.
func FindAppPlaybookP(exec boil.Executor, id int64, selectCols ...string) *AppPlaybook {
	retobj, err := FindAppPlaybook(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *AppPlaybook) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *AppPlaybook) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *AppPlaybook) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *AppPlaybook) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no app_playbook provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(appPlaybookColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	appPlaybookInsertCacheMut.RLock()
	cache, cached := appPlaybookInsertCache[key]
	appPlaybookInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			appPlaybookColumns,
			appPlaybookColumnsWithDefault,
			appPlaybookColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(appPlaybookType, appPlaybookMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(appPlaybookType, appPlaybookMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `app_playbook` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `app_playbook` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `app_playbook` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, appPlaybookPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into app_playbook")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == appPlaybookMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for app_playbook")
	}

CacheNoHooks:
	if !cached {
		appPlaybookInsertCacheMut.Lock()
		appPlaybookInsertCache[key] = cache
		appPlaybookInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single AppPlaybook record. See Update for
// whitelist behavior description.
func (o *AppPlaybook) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single AppPlaybook record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *AppPlaybook) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the AppPlaybook, and panics on error.
// See Update for whitelist behavior description.
func (o *AppPlaybook) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the AppPlaybook.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *AppPlaybook) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	appPlaybookUpdateCacheMut.RLock()
	cache, cached := appPlaybookUpdateCache[key]
	appPlaybookUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			appPlaybookColumns,
			appPlaybookPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update app_playbook, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `app_playbook` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, appPlaybookPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(appPlaybookType, appPlaybookMapping, append(wl, appPlaybookPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update app_playbook row")
	}

	if !cached {
		appPlaybookUpdateCacheMut.Lock()
		appPlaybookUpdateCache[key] = cache
		appPlaybookUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q appPlaybookQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q appPlaybookQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for app_playbook")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o AppPlaybookSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o AppPlaybookSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o AppPlaybookSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AppPlaybookSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), appPlaybookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `app_playbook` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, appPlaybookPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in appPlaybook slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *AppPlaybook) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *AppPlaybook) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *AppPlaybook) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *AppPlaybook) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no app_playbook provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(appPlaybookColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	appPlaybookUpsertCacheMut.RLock()
	cache, cached := appPlaybookUpsertCache[key]
	appPlaybookUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			appPlaybookColumns,
			appPlaybookColumnsWithDefault,
			appPlaybookColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			appPlaybookColumns,
			appPlaybookPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert app_playbook, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "app_playbook", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `app_playbook` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(appPlaybookType, appPlaybookMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(appPlaybookType, appPlaybookMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for app_playbook")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == appPlaybookMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for app_playbook")
	}

CacheNoHooks:
	if !cached {
		appPlaybookUpsertCacheMut.Lock()
		appPlaybookUpsertCache[key] = cache
		appPlaybookUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single AppPlaybook record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *AppPlaybook) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single AppPlaybook record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *AppPlaybook) DeleteG() error {
	if o == nil {
		return errors.New("models: no AppPlaybook provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single AppPlaybook record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *AppPlaybook) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single AppPlaybook record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AppPlaybook) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no AppPlaybook provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), appPlaybookPrimaryKeyMapping)
	sql := "DELETE FROM `app_playbook` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from app_playbook")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q appPlaybookQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q appPlaybookQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no appPlaybookQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from app_playbook")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o AppPlaybookSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o AppPlaybookSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no AppPlaybook slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o AppPlaybookSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AppPlaybookSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no AppPlaybook slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(appPlaybookBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), appPlaybookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `app_playbook` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, appPlaybookPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from appPlaybook slice")
	}

	if len(appPlaybookAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *AppPlaybook) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *AppPlaybook) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *AppPlaybook) ReloadG() error {
	if o == nil {
		return errors.New("models: no AppPlaybook provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AppPlaybook) Reload(exec boil.Executor) error {
	ret, err := FindAppPlaybook(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AppPlaybookSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *AppPlaybookSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AppPlaybookSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty AppPlaybookSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AppPlaybookSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	appPlaybooks := AppPlaybookSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), appPlaybookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `app_playbook`.* FROM `app_playbook` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, appPlaybookPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&appPlaybooks)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in AppPlaybookSlice")
	}

	*o = appPlaybooks

	return nil
}

// AppPlaybookExists checks if the AppPlaybook row exists.
func AppPlaybookExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `app_playbook` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if app_playbook exists")
	}

	return exists, nil
}

// AppPlaybookExistsG checks if the AppPlaybook row exists.
func AppPlaybookExistsG(id int64) (bool, error) {
	return AppPlaybookExists(boil.GetDB(), id)
}

// AppPlaybookExistsGP checks if the AppPlaybook row exists. Panics on error.
func AppPlaybookExistsGP(id int64) bool {
	e, err := AppPlaybookExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// AppPlaybookExistsP checks if the AppPlaybook row exists. Panics on error.
func AppPlaybookExistsP(exec boil.Executor, id int64) bool {
	e, err := AppPlaybookExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
