// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	App          string
	AppInventory string
	AppPlaybook  string
	Failure      string
	Inventory    string
	Job          string
	Playbook     string
	Run          string
	Statistics   string
}{
	App:          "app",
	AppInventory: "app_inventory",
	AppPlaybook:  "app_playbook",
	Failure:      "failure",
	Inventory:    "inventory",
	Job:          "job",
	Playbook:     "playbook",
	Run:          "run",
	Statistics:   "statistics",
}
