// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Failure is an object representing the database table.
type Failure struct {
	ID           int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DRCCheckTime time.Time `boil:"drc_check_time" json:"drc_check_time" toml:"drc_check_time" yaml:"drc_check_time"`
	StatsID      int64     `boil:"stats_id" json:"stats_id" toml:"stats_id" yaml:"stats_id"`
	Result       string    `boil:"result" json:"result" toml:"result" yaml:"result"`

	R *failureR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L failureL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FailureColumns = struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	DRCCheckTime string
	StatsID      string
	Result       string
}{
	ID:           "id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DRCCheckTime: "drc_check_time",
	StatsID:      "stats_id",
	Result:       "result",
}

// failureR is where relationships are stored.
type failureR struct {
}

// failureL is where Load methods for each relationship are stored.
type failureL struct{}

var (
	failureColumns               = []string{"id", "created_at", "updated_at", "drc_check_time", "stats_id", "result"}
	failureColumnsWithoutDefault = []string{"result"}
	failureColumnsWithDefault    = []string{"id", "created_at", "updated_at", "drc_check_time", "stats_id"}
	failurePrimaryKeyColumns     = []string{"id"}
)

type (
	// FailureSlice is an alias for a slice of pointers to Failure.
	// This should generally be used opposed to []Failure.
	FailureSlice []*Failure
	// FailureHook is the signature for custom Failure hook methods
	FailureHook func(boil.Executor, *Failure) error

	failureQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	failureType                 = reflect.TypeOf(&Failure{})
	failureMapping              = queries.MakeStructMapping(failureType)
	failurePrimaryKeyMapping, _ = queries.BindMapping(failureType, failureMapping, failurePrimaryKeyColumns)
	failureInsertCacheMut       sync.RWMutex
	failureInsertCache          = make(map[string]insertCache)
	failureUpdateCacheMut       sync.RWMutex
	failureUpdateCache          = make(map[string]updateCache)
	failureUpsertCacheMut       sync.RWMutex
	failureUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var failureBeforeInsertHooks []FailureHook
var failureBeforeUpdateHooks []FailureHook
var failureBeforeDeleteHooks []FailureHook
var failureBeforeUpsertHooks []FailureHook

var failureAfterInsertHooks []FailureHook
var failureAfterSelectHooks []FailureHook
var failureAfterUpdateHooks []FailureHook
var failureAfterDeleteHooks []FailureHook
var failureAfterUpsertHooks []FailureHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Failure) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range failureBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Failure) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range failureBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Failure) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range failureBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Failure) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range failureBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Failure) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range failureAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Failure) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range failureAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Failure) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range failureAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Failure) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range failureAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Failure) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range failureAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFailureHook registers your hook function for all future operations.
func AddFailureHook(hookPoint boil.HookPoint, failureHook FailureHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		failureBeforeInsertHooks = append(failureBeforeInsertHooks, failureHook)
	case boil.BeforeUpdateHook:
		failureBeforeUpdateHooks = append(failureBeforeUpdateHooks, failureHook)
	case boil.BeforeDeleteHook:
		failureBeforeDeleteHooks = append(failureBeforeDeleteHooks, failureHook)
	case boil.BeforeUpsertHook:
		failureBeforeUpsertHooks = append(failureBeforeUpsertHooks, failureHook)
	case boil.AfterInsertHook:
		failureAfterInsertHooks = append(failureAfterInsertHooks, failureHook)
	case boil.AfterSelectHook:
		failureAfterSelectHooks = append(failureAfterSelectHooks, failureHook)
	case boil.AfterUpdateHook:
		failureAfterUpdateHooks = append(failureAfterUpdateHooks, failureHook)
	case boil.AfterDeleteHook:
		failureAfterDeleteHooks = append(failureAfterDeleteHooks, failureHook)
	case boil.AfterUpsertHook:
		failureAfterUpsertHooks = append(failureAfterUpsertHooks, failureHook)
	}
}

// OneP returns a single failure record from the query, and panics on error.
func (q failureQuery) OneP() *Failure {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single failure record from the query.
func (q failureQuery) One() (*Failure, error) {
	o := &Failure{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for failure")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Failure records from the query, and panics on error.
func (q failureQuery) AllP() FailureSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Failure records from the query.
func (q failureQuery) All() (FailureSlice, error) {
	var o []*Failure

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Failure slice")
	}

	if len(failureAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Failure records in the query, and panics on error.
func (q failureQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Failure records in the query.
func (q failureQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count failure rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q failureQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q failureQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if failure exists")
	}

	return count > 0, nil
}

// FailuresG retrieves all records.
func FailuresG(mods ...qm.QueryMod) failureQuery {
	return Failures(boil.GetDB(), mods...)
}

// Failures retrieves all the records using an executor.
func Failures(exec boil.Executor, mods ...qm.QueryMod) failureQuery {
	mods = append(mods, qm.From("`failure`"))
	return failureQuery{NewQuery(exec, mods...)}
}

// FindFailureG retrieves a single record by ID.
func FindFailureG(id int64, selectCols ...string) (*Failure, error) {
	return FindFailure(boil.GetDB(), id, selectCols...)
}

// FindFailureGP retrieves a single record by ID, and panics on error.
func FindFailureGP(id int64, selectCols ...string) *Failure {
	retobj, err := FindFailure(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindFailure retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFailure(exec boil.Executor, id int64, selectCols ...string) (*Failure, error) {
	failureObj := &Failure{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `failure` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(failureObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from failure")
	}

	return failureObj, nil
}

// FindFailureP retrieves a single record by ID with an executor, and panics on error.
func FindFailureP(exec boil.Executor, id int64, selectCols ...string) *Failure {
	retobj, err := FindFailure(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Failure) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Failure) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Failure) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Failure) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no failure provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(failureColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	failureInsertCacheMut.RLock()
	cache, cached := failureInsertCache[key]
	failureInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			failureColumns,
			failureColumnsWithDefault,
			failureColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(failureType, failureMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(failureType, failureMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `failure` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `failure` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `failure` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, failurePrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into failure")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == failureMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for failure")
	}

CacheNoHooks:
	if !cached {
		failureInsertCacheMut.Lock()
		failureInsertCache[key] = cache
		failureInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Failure record. See Update for
// whitelist behavior description.
func (o *Failure) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Failure record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Failure) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Failure, and panics on error.
// See Update for whitelist behavior description.
func (o *Failure) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Failure.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Failure) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	failureUpdateCacheMut.RLock()
	cache, cached := failureUpdateCache[key]
	failureUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			failureColumns,
			failurePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update failure, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `failure` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, failurePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(failureType, failureMapping, append(wl, failurePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update failure row")
	}

	if !cached {
		failureUpdateCacheMut.Lock()
		failureUpdateCache[key] = cache
		failureUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q failureQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q failureQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for failure")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o FailureSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o FailureSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o FailureSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FailureSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), failurePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `failure` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, failurePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in failure slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Failure) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Failure) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Failure) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Failure) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no failure provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(failureColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	failureUpsertCacheMut.RLock()
	cache, cached := failureUpsertCache[key]
	failureUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			failureColumns,
			failureColumnsWithDefault,
			failureColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			failureColumns,
			failurePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert failure, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "failure", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `failure` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(failureType, failureMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(failureType, failureMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for failure")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == failureMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for failure")
	}

CacheNoHooks:
	if !cached {
		failureUpsertCacheMut.Lock()
		failureUpsertCache[key] = cache
		failureUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Failure record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Failure) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Failure record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Failure) DeleteG() error {
	if o == nil {
		return errors.New("models: no Failure provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Failure record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Failure) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Failure record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Failure) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Failure provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), failurePrimaryKeyMapping)
	sql := "DELETE FROM `failure` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from failure")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q failureQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q failureQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no failureQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from failure")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o FailureSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o FailureSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Failure slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o FailureSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FailureSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Failure slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(failureBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), failurePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `failure` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, failurePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from failure slice")
	}

	if len(failureAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Failure) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Failure) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Failure) ReloadG() error {
	if o == nil {
		return errors.New("models: no Failure provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Failure) Reload(exec boil.Executor) error {
	ret, err := FindFailure(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *FailureSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *FailureSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FailureSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty FailureSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FailureSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	failures := FailureSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), failurePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `failure`.* FROM `failure` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, failurePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&failures)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FailureSlice")
	}

	*o = failures

	return nil
}

// FailureExists checks if the Failure row exists.
func FailureExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `failure` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if failure exists")
	}

	return exists, nil
}

// FailureExistsG checks if the Failure row exists.
func FailureExistsG(id int64) (bool, error) {
	return FailureExists(boil.GetDB(), id)
}

// FailureExistsGP checks if the Failure row exists. Panics on error.
func FailureExistsGP(id int64) bool {
	e, err := FailureExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// FailureExistsP checks if the Failure row exists. Panics on error.
func FailureExistsP(exec boil.Executor, id int64) bool {
	e, err := FailureExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
