// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Playbook is an object representing the database table.
type Playbook struct {
	ID           int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DRCCheckTime time.Time `boil:"drc_check_time" json:"drc_check_time" toml:"drc_check_time" yaml:"drc_check_time"`
	Name         string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	GitRepo      string    `boil:"git_repo" json:"git_repo" toml:"git_repo" yaml:"git_repo"`
	Entry        string    `boil:"entry" json:"entry" toml:"entry" yaml:"entry"`

	R *playbookR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L playbookL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PlaybookColumns = struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	DRCCheckTime string
	Name         string
	GitRepo      string
	Entry        string
}{
	ID:           "id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DRCCheckTime: "drc_check_time",
	Name:         "name",
	GitRepo:      "git_repo",
	Entry:        "entry",
}

// playbookR is where relationships are stored.
type playbookR struct {
}

// playbookL is where Load methods for each relationship are stored.
type playbookL struct{}

var (
	playbookColumns               = []string{"id", "created_at", "updated_at", "drc_check_time", "name", "git_repo", "entry"}
	playbookColumnsWithoutDefault = []string{"name", "git_repo"}
	playbookColumnsWithDefault    = []string{"id", "created_at", "updated_at", "drc_check_time", "entry"}
	playbookPrimaryKeyColumns     = []string{"id"}
)

type (
	// PlaybookSlice is an alias for a slice of pointers to Playbook.
	// This should generally be used opposed to []Playbook.
	PlaybookSlice []*Playbook
	// PlaybookHook is the signature for custom Playbook hook methods
	PlaybookHook func(boil.Executor, *Playbook) error

	playbookQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	playbookType                 = reflect.TypeOf(&Playbook{})
	playbookMapping              = queries.MakeStructMapping(playbookType)
	playbookPrimaryKeyMapping, _ = queries.BindMapping(playbookType, playbookMapping, playbookPrimaryKeyColumns)
	playbookInsertCacheMut       sync.RWMutex
	playbookInsertCache          = make(map[string]insertCache)
	playbookUpdateCacheMut       sync.RWMutex
	playbookUpdateCache          = make(map[string]updateCache)
	playbookUpsertCacheMut       sync.RWMutex
	playbookUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var playbookBeforeInsertHooks []PlaybookHook
var playbookBeforeUpdateHooks []PlaybookHook
var playbookBeforeDeleteHooks []PlaybookHook
var playbookBeforeUpsertHooks []PlaybookHook

var playbookAfterInsertHooks []PlaybookHook
var playbookAfterSelectHooks []PlaybookHook
var playbookAfterUpdateHooks []PlaybookHook
var playbookAfterDeleteHooks []PlaybookHook
var playbookAfterUpsertHooks []PlaybookHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Playbook) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Playbook) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Playbook) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Playbook) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Playbook) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Playbook) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Playbook) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Playbook) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Playbook) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range playbookAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPlaybookHook registers your hook function for all future operations.
func AddPlaybookHook(hookPoint boil.HookPoint, playbookHook PlaybookHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		playbookBeforeInsertHooks = append(playbookBeforeInsertHooks, playbookHook)
	case boil.BeforeUpdateHook:
		playbookBeforeUpdateHooks = append(playbookBeforeUpdateHooks, playbookHook)
	case boil.BeforeDeleteHook:
		playbookBeforeDeleteHooks = append(playbookBeforeDeleteHooks, playbookHook)
	case boil.BeforeUpsertHook:
		playbookBeforeUpsertHooks = append(playbookBeforeUpsertHooks, playbookHook)
	case boil.AfterInsertHook:
		playbookAfterInsertHooks = append(playbookAfterInsertHooks, playbookHook)
	case boil.AfterSelectHook:
		playbookAfterSelectHooks = append(playbookAfterSelectHooks, playbookHook)
	case boil.AfterUpdateHook:
		playbookAfterUpdateHooks = append(playbookAfterUpdateHooks, playbookHook)
	case boil.AfterDeleteHook:
		playbookAfterDeleteHooks = append(playbookAfterDeleteHooks, playbookHook)
	case boil.AfterUpsertHook:
		playbookAfterUpsertHooks = append(playbookAfterUpsertHooks, playbookHook)
	}
}

// OneP returns a single playbook record from the query, and panics on error.
func (q playbookQuery) OneP() *Playbook {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single playbook record from the query.
func (q playbookQuery) One() (*Playbook, error) {
	o := &Playbook{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for playbook")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Playbook records from the query, and panics on error.
func (q playbookQuery) AllP() PlaybookSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Playbook records from the query.
func (q playbookQuery) All() (PlaybookSlice, error) {
	var o []*Playbook

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Playbook slice")
	}

	if len(playbookAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Playbook records in the query, and panics on error.
func (q playbookQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Playbook records in the query.
func (q playbookQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count playbook rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q playbookQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q playbookQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if playbook exists")
	}

	return count > 0, nil
}

// PlaybooksG retrieves all records.
func PlaybooksG(mods ...qm.QueryMod) playbookQuery {
	return Playbooks(boil.GetDB(), mods...)
}

// Playbooks retrieves all the records using an executor.
func Playbooks(exec boil.Executor, mods ...qm.QueryMod) playbookQuery {
	mods = append(mods, qm.From("`playbook`"))
	return playbookQuery{NewQuery(exec, mods...)}
}

// FindPlaybookG retrieves a single record by ID.
func FindPlaybookG(id int64, selectCols ...string) (*Playbook, error) {
	return FindPlaybook(boil.GetDB(), id, selectCols...)
}

// FindPlaybookGP retrieves a single record by ID, and panics on error.
func FindPlaybookGP(id int64, selectCols ...string) *Playbook {
	retobj, err := FindPlaybook(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindPlaybook retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPlaybook(exec boil.Executor, id int64, selectCols ...string) (*Playbook, error) {
	playbookObj := &Playbook{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `playbook` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(playbookObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from playbook")
	}

	return playbookObj, nil
}

// FindPlaybookP retrieves a single record by ID with an executor, and panics on error.
func FindPlaybookP(exec boil.Executor, id int64, selectCols ...string) *Playbook {
	retobj, err := FindPlaybook(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Playbook) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Playbook) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Playbook) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Playbook) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no playbook provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(playbookColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	playbookInsertCacheMut.RLock()
	cache, cached := playbookInsertCache[key]
	playbookInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			playbookColumns,
			playbookColumnsWithDefault,
			playbookColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(playbookType, playbookMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(playbookType, playbookMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `playbook` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `playbook` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `playbook` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, playbookPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into playbook")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == playbookMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for playbook")
	}

CacheNoHooks:
	if !cached {
		playbookInsertCacheMut.Lock()
		playbookInsertCache[key] = cache
		playbookInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Playbook record. See Update for
// whitelist behavior description.
func (o *Playbook) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Playbook record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Playbook) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Playbook, and panics on error.
// See Update for whitelist behavior description.
func (o *Playbook) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Playbook.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Playbook) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	playbookUpdateCacheMut.RLock()
	cache, cached := playbookUpdateCache[key]
	playbookUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			playbookColumns,
			playbookPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update playbook, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `playbook` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, playbookPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(playbookType, playbookMapping, append(wl, playbookPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update playbook row")
	}

	if !cached {
		playbookUpdateCacheMut.Lock()
		playbookUpdateCache[key] = cache
		playbookUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q playbookQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q playbookQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for playbook")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o PlaybookSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o PlaybookSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o PlaybookSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PlaybookSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), playbookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `playbook` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, playbookPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in playbook slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Playbook) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Playbook) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Playbook) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Playbook) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no playbook provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(playbookColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	playbookUpsertCacheMut.RLock()
	cache, cached := playbookUpsertCache[key]
	playbookUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			playbookColumns,
			playbookColumnsWithDefault,
			playbookColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			playbookColumns,
			playbookPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert playbook, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "playbook", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `playbook` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(playbookType, playbookMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(playbookType, playbookMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for playbook")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == playbookMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for playbook")
	}

CacheNoHooks:
	if !cached {
		playbookUpsertCacheMut.Lock()
		playbookUpsertCache[key] = cache
		playbookUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Playbook record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Playbook) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Playbook record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Playbook) DeleteG() error {
	if o == nil {
		return errors.New("models: no Playbook provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Playbook record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Playbook) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Playbook record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Playbook) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Playbook provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), playbookPrimaryKeyMapping)
	sql := "DELETE FROM `playbook` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from playbook")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q playbookQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q playbookQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no playbookQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from playbook")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o PlaybookSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o PlaybookSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Playbook slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o PlaybookSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PlaybookSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Playbook slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(playbookBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), playbookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `playbook` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, playbookPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from playbook slice")
	}

	if len(playbookAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Playbook) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Playbook) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Playbook) ReloadG() error {
	if o == nil {
		return errors.New("models: no Playbook provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Playbook) Reload(exec boil.Executor) error {
	ret, err := FindPlaybook(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *PlaybookSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *PlaybookSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PlaybookSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty PlaybookSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PlaybookSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	playbooks := PlaybookSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), playbookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `playbook`.* FROM `playbook` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, playbookPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&playbooks)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PlaybookSlice")
	}

	*o = playbooks

	return nil
}

// PlaybookExists checks if the Playbook row exists.
func PlaybookExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `playbook` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if playbook exists")
	}

	return exists, nil
}

// PlaybookExistsG checks if the Playbook row exists.
func PlaybookExistsG(id int64) (bool, error) {
	return PlaybookExists(boil.GetDB(), id)
}

// PlaybookExistsGP checks if the Playbook row exists. Panics on error.
func PlaybookExistsGP(id int64) bool {
	e, err := PlaybookExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// PlaybookExistsP checks if the Playbook row exists. Panics on error.
func PlaybookExistsP(exec boil.Executor, id int64) bool {
	e, err := PlaybookExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
