// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Statistic is an object representing the database table.
type Statistic struct {
	ID           int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DRCCheckTime time.Time `boil:"drc_check_time" json:"drc_check_time" toml:"drc_check_time" yaml:"drc_check_time"`
	JobStartTime time.Time `boil:"job_start_time" json:"job_start_time" toml:"job_start_time" yaml:"job_start_time"`
	RunID        string    `boil:"run_id" json:"run_id" toml:"run_id" yaml:"run_id"`
	Target       string    `boil:"target" json:"target" toml:"target" yaml:"target"`
	Unreachable  bool      `boil:"unreachable" json:"unreachable" toml:"unreachable" yaml:"unreachable"`
	Failed       int       `boil:"failed" json:"failed" toml:"failed" yaml:"failed"`

	R *statisticR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L statisticL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var StatisticColumns = struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	DRCCheckTime string
	JobStartTime string
	RunID        string
	Target       string
	Unreachable  string
	Failed       string
}{
	ID:           "id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DRCCheckTime: "drc_check_time",
	JobStartTime: "job_start_time",
	RunID:        "run_id",
	Target:       "target",
	Unreachable:  "unreachable",
	Failed:       "failed",
}

// statisticR is where relationships are stored.
type statisticR struct {
}

// statisticL is where Load methods for each relationship are stored.
type statisticL struct{}

var (
	statisticColumns               = []string{"id", "created_at", "updated_at", "drc_check_time", "job_start_time", "run_id", "target", "unreachable", "failed"}
	statisticColumnsWithoutDefault = []string{"run_id", "target"}
	statisticColumnsWithDefault    = []string{"id", "created_at", "updated_at", "drc_check_time", "job_start_time", "unreachable", "failed"}
	statisticPrimaryKeyColumns     = []string{"id"}
)

type (
	// StatisticSlice is an alias for a slice of pointers to Statistic.
	// This should generally be used opposed to []Statistic.
	StatisticSlice []*Statistic
	// StatisticHook is the signature for custom Statistic hook methods
	StatisticHook func(boil.Executor, *Statistic) error

	statisticQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	statisticType                 = reflect.TypeOf(&Statistic{})
	statisticMapping              = queries.MakeStructMapping(statisticType)
	statisticPrimaryKeyMapping, _ = queries.BindMapping(statisticType, statisticMapping, statisticPrimaryKeyColumns)
	statisticInsertCacheMut       sync.RWMutex
	statisticInsertCache          = make(map[string]insertCache)
	statisticUpdateCacheMut       sync.RWMutex
	statisticUpdateCache          = make(map[string]updateCache)
	statisticUpsertCacheMut       sync.RWMutex
	statisticUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var statisticBeforeInsertHooks []StatisticHook
var statisticBeforeUpdateHooks []StatisticHook
var statisticBeforeDeleteHooks []StatisticHook
var statisticBeforeUpsertHooks []StatisticHook

var statisticAfterInsertHooks []StatisticHook
var statisticAfterSelectHooks []StatisticHook
var statisticAfterUpdateHooks []StatisticHook
var statisticAfterDeleteHooks []StatisticHook
var statisticAfterUpsertHooks []StatisticHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Statistic) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Statistic) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Statistic) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Statistic) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Statistic) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Statistic) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Statistic) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Statistic) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Statistic) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range statisticAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddStatisticHook registers your hook function for all future operations.
func AddStatisticHook(hookPoint boil.HookPoint, statisticHook StatisticHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		statisticBeforeInsertHooks = append(statisticBeforeInsertHooks, statisticHook)
	case boil.BeforeUpdateHook:
		statisticBeforeUpdateHooks = append(statisticBeforeUpdateHooks, statisticHook)
	case boil.BeforeDeleteHook:
		statisticBeforeDeleteHooks = append(statisticBeforeDeleteHooks, statisticHook)
	case boil.BeforeUpsertHook:
		statisticBeforeUpsertHooks = append(statisticBeforeUpsertHooks, statisticHook)
	case boil.AfterInsertHook:
		statisticAfterInsertHooks = append(statisticAfterInsertHooks, statisticHook)
	case boil.AfterSelectHook:
		statisticAfterSelectHooks = append(statisticAfterSelectHooks, statisticHook)
	case boil.AfterUpdateHook:
		statisticAfterUpdateHooks = append(statisticAfterUpdateHooks, statisticHook)
	case boil.AfterDeleteHook:
		statisticAfterDeleteHooks = append(statisticAfterDeleteHooks, statisticHook)
	case boil.AfterUpsertHook:
		statisticAfterUpsertHooks = append(statisticAfterUpsertHooks, statisticHook)
	}
}

// OneP returns a single statistic record from the query, and panics on error.
func (q statisticQuery) OneP() *Statistic {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single statistic record from the query.
func (q statisticQuery) One() (*Statistic, error) {
	o := &Statistic{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for statistics")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Statistic records from the query, and panics on error.
func (q statisticQuery) AllP() StatisticSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Statistic records from the query.
func (q statisticQuery) All() (StatisticSlice, error) {
	var o []*Statistic

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Statistic slice")
	}

	if len(statisticAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Statistic records in the query, and panics on error.
func (q statisticQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Statistic records in the query.
func (q statisticQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count statistics rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q statisticQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q statisticQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if statistics exists")
	}

	return count > 0, nil
}

// StatisticsG retrieves all records.
func StatisticsG(mods ...qm.QueryMod) statisticQuery {
	return Statistics(boil.GetDB(), mods...)
}

// Statistics retrieves all the records using an executor.
func Statistics(exec boil.Executor, mods ...qm.QueryMod) statisticQuery {
	mods = append(mods, qm.From("`statistics`"))
	return statisticQuery{NewQuery(exec, mods...)}
}

// FindStatisticG retrieves a single record by ID.
func FindStatisticG(id int64, selectCols ...string) (*Statistic, error) {
	return FindStatistic(boil.GetDB(), id, selectCols...)
}

// FindStatisticGP retrieves a single record by ID, and panics on error.
func FindStatisticGP(id int64, selectCols ...string) *Statistic {
	retobj, err := FindStatistic(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindStatistic retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindStatistic(exec boil.Executor, id int64, selectCols ...string) (*Statistic, error) {
	statisticObj := &Statistic{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `statistics` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(statisticObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from statistics")
	}

	return statisticObj, nil
}

// FindStatisticP retrieves a single record by ID with an executor, and panics on error.
func FindStatisticP(exec boil.Executor, id int64, selectCols ...string) *Statistic {
	retobj, err := FindStatistic(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Statistic) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Statistic) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Statistic) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Statistic) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no statistics provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(statisticColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	statisticInsertCacheMut.RLock()
	cache, cached := statisticInsertCache[key]
	statisticInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			statisticColumns,
			statisticColumnsWithDefault,
			statisticColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(statisticType, statisticMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(statisticType, statisticMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `statistics` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `statistics` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `statistics` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, statisticPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into statistics")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == statisticMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for statistics")
	}

CacheNoHooks:
	if !cached {
		statisticInsertCacheMut.Lock()
		statisticInsertCache[key] = cache
		statisticInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Statistic record. See Update for
// whitelist behavior description.
func (o *Statistic) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Statistic record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Statistic) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Statistic, and panics on error.
// See Update for whitelist behavior description.
func (o *Statistic) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Statistic.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Statistic) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	statisticUpdateCacheMut.RLock()
	cache, cached := statisticUpdateCache[key]
	statisticUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			statisticColumns,
			statisticPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update statistics, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `statistics` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, statisticPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(statisticType, statisticMapping, append(wl, statisticPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update statistics row")
	}

	if !cached {
		statisticUpdateCacheMut.Lock()
		statisticUpdateCache[key] = cache
		statisticUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q statisticQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q statisticQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for statistics")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o StatisticSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o StatisticSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o StatisticSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o StatisticSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), statisticPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `statistics` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, statisticPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in statistic slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Statistic) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Statistic) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Statistic) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Statistic) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no statistics provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(statisticColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	statisticUpsertCacheMut.RLock()
	cache, cached := statisticUpsertCache[key]
	statisticUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			statisticColumns,
			statisticColumnsWithDefault,
			statisticColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			statisticColumns,
			statisticPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert statistics, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "statistics", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `statistics` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(statisticType, statisticMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(statisticType, statisticMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for statistics")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == statisticMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for statistics")
	}

CacheNoHooks:
	if !cached {
		statisticUpsertCacheMut.Lock()
		statisticUpsertCache[key] = cache
		statisticUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Statistic record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Statistic) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Statistic record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Statistic) DeleteG() error {
	if o == nil {
		return errors.New("models: no Statistic provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Statistic record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Statistic) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Statistic record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Statistic) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Statistic provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), statisticPrimaryKeyMapping)
	sql := "DELETE FROM `statistics` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from statistics")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q statisticQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q statisticQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no statisticQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from statistics")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o StatisticSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o StatisticSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Statistic slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o StatisticSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o StatisticSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Statistic slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(statisticBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), statisticPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `statistics` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, statisticPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from statistic slice")
	}

	if len(statisticAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Statistic) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Statistic) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Statistic) ReloadG() error {
	if o == nil {
		return errors.New("models: no Statistic provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Statistic) Reload(exec boil.Executor) error {
	ret, err := FindStatistic(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *StatisticSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *StatisticSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StatisticSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty StatisticSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StatisticSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	statistics := StatisticSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), statisticPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `statistics`.* FROM `statistics` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, statisticPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&statistics)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in StatisticSlice")
	}

	*o = statistics

	return nil
}

// StatisticExists checks if the Statistic row exists.
func StatisticExists(exec boil.Executor, id int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `statistics` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if statistics exists")
	}

	return exists, nil
}

// StatisticExistsG checks if the Statistic row exists.
func StatisticExistsG(id int64) (bool, error) {
	return StatisticExists(boil.GetDB(), id)
}

// StatisticExistsGP checks if the Statistic row exists. Panics on error.
func StatisticExistsGP(id int64) bool {
	e, err := StatisticExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// StatisticExistsP checks if the Statistic row exists. Panics on error.
func StatisticExistsP(exec boil.Executor, id int64) bool {
	e, err := StatisticExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
